//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtiklPrimka
    {
        public long artiklId { get; set; }
        public int primkaId { get; set; }
        public Nullable<int> dobavljacId { get; set; }
        public Nullable<int> skladisteId { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<byte> zaprimljeno { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Dobavljac Dobavljac { get; set; }
        public virtual Primka Primka { get; set; }
        public virtual Skladiste Skladiste { get; set; }
    }
}
