//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtiklPovratnica
    {
        public long artiklId { get; set; }
        public int povratnicaId { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<decimal> cijena { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Povratnica Povratnica { get; set; }
    }
}
