//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventura
    {
        public int id { get; set; }
        public Nullable<int> korisnikId { get; set; }
        public Nullable<int> trgovinaId { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> primkaKolicina { get; set; }
        public Nullable<decimal> primkaCijena { get; set; }
        public Nullable<int> povratnicaKolicina { get; set; }
        public Nullable<decimal> povratnicaCijena { get; set; }
        public Nullable<int> racunKolicina { get; set; }
        public Nullable<decimal> racunCijena { get; set; }
        public Nullable<int> skladisteKolicina { get; set; }
        public Nullable<decimal> skladisteCijena { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Trgovina Trgovina { get; set; }
    }
}
