//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database : DbContext
    {
        public Database()
            : base("name=Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikl> Artikls { get; set; }
        public virtual DbSet<ArtiklCijena> ArtiklCijenas { get; set; }
        public virtual DbSet<ArtiklNarudzbenica> ArtiklNarudzbenicas { get; set; }
        public virtual DbSet<ArtiklPovratnica> ArtiklPovratnicas { get; set; }
        public virtual DbSet<ArtiklPrimka> ArtiklPrimkas { get; set; }
        public virtual DbSet<ArtiklSkladiste> ArtiklSkladistes { get; set; }
        public virtual DbSet<Dobavljac> Dobavljacs { get; set; }
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<Inventura> Inventuras { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Lokacija> Lokacijas { get; set; }
        public virtual DbSet<Narudzbenica> Narudzbenicas { get; set; }
        public virtual DbSet<Povratnica> Povratnicas { get; set; }
        public virtual DbSet<Primka> Primkas { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<RacunArtikl> RacunArtikls { get; set; }
        public virtual DbSet<Satnica> Satnicas { get; set; }
        public virtual DbSet<Skladiste> Skladistes { get; set; }
        public virtual DbSet<Trgovina> Trgovinas { get; set; }
        public virtual DbSet<VrstaKorisnika> VrstaKorisnikas { get; set; }
    }
}
