//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satnica
    {
        public int id { get; set; }
        public Nullable<int> korisnikId { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> brojSati { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
